/**
 * Configuration for embedding providers
 */
export interface EmbedderConfig {
    // Base configuration
    modelName: string;
    maxTokens: number;
    batchSize: number;
    
    // Optional provider-specific settings
    apiKey?: string;
    baseURL?: string;
    customOptions?: Record<string, any>;
}

/**
 * Interface for embedding providers
 */
export interface IEmbedder {
    /**
     * Generate embeddings for one or more texts
     * @param texts Single text or array of texts to generate embeddings for
     * @returns Promise resolving to array of embeddings
     */
    generateEmbeddings(texts: string | string[]): Promise<number[][]>;
    
    /**
     * Get the dimension of embeddings generated by this provider
     */
    getEmbeddingDimension(): number;
    
    /**
     * Get the maximum number of tokens this provider can handle
     */
    getMaxTokens(): number;
    
    /**
     * Clear any cached data and resources
     */
    clear(): Promise<void>;
}
